version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: library
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mongodb_network

volumes:
  mongo_data:

networks:
  mongodb_network:
    driver: bridge