spring:
  data:
    mongodb:
      uri: mongodb://rootuser:rootpassword@localhost:27017/library?authSource=admin
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.mongodb.driver: INFO